[package]
name = "proc"
version = "0.1.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/danburkert/proc-rs"
documentation = "https://danburkert.github.io/proc-rs/proc/index.html"
description = "A library for accessing Linux process and system information"
keywords = ["proc", "process", "system", "Linux"]
exclude = [
  ".gitignore",
  ".travis.yml",
]

[dependencies]
nom = "0.3"
byteorder = "0.3"
