[package]
name = "procinfo"
version = "0.2.2"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/danburkert/procinfo-rs"
documentation = "https://danburkert.github.io/procinfo-rs/procinfo/index.html"
description = "A library for accessing Linux process and system information"
keywords = ["proc", "process", "system", "Linux"]
exclude = [
  ".gitignore",
  ".travis.yml",
]

[dependencies]
libc = "0.2"
nom = "1"
byteorder = "0.5"
